### ISSUE TITLE
Could you share the project code for L4D2?

### ISSUE THREAD

**Issue by xiluotop** [Haze1337/sendproxy_archive#1]
I tried to recompile it but the prompt is as follows:

 error LNK2019: unresolved external symbol _ud_set_mode referenced in function _copy_bytes
 error LNK2019: unresolved external symbol _ud_set_input_buffer referenced in function _copy_bytes
 error LNK2019: unresolved external symbol _ud_disassemble referenced in function _copy_bytes
 error LNK2019: unresolved external symbol _ud_insn_ptr referenced in function _copy_bytes
 error LNK2019: unresolved external symbol _ud_insn_len referenced in function _copy_bytes
 error LNK2019: unresolved external symbol _ud_insn_opr referenced in function _copy_bytes

Please help me~~

**Comment by Haze1337** [comment]
Release version was compiled with Github Actions, so idk
https://github.com/Haze1337/sendproxy_archive/actions/runs/2862036573
https://github.com/Haze1337/sendproxy_archive/blob/main/.github/workflows/main.yml

**Comment by xiluotop** [comment]
Thanks a lot, It work well, you are awesome!
